export const VIDEO_TYPE_CHOICES = {
  VIDEO_TYPE_ANIME: "Anime",
  VIDEO_TYPE_MOVIE: "Movie",
  VIDEO_TYPE_SERIAL: "Serial",
};

export const VIDEO_STATUS_CHOICES = {
  VIDEO_STATUS_FINISHED: "Finished",
  VIDEO_STATUS_WATCHING: "Watching",
  VIDEO_STATUS_WILL_WATCH: "Will Watch",
  VIDEO_STATUS_UNINTERESTED: "Uninterested",
};
